metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
replication_factor = 1

rpc_bind_addr = "[::]:3902"
rpc_public_addr = "garage:3902"
rpc_secret = "0000000000000000000000000000000000000000000000000000000000000000"

[s3_api]
api_bind_addr = "[::]:3900"
s3_region = "garage"

[admin]
api_bind_addr = "[::]:3901"
admin_token = "resize-it-garage-admin"
metrics_token = "resize-it-garage-metrics"
